<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN9z0fVx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN9z0fVx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerN9z0fVx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerN9z0fVx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerN9z0fVx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'N9z0fVx',
    'container.build_id' => '7e71c0d3',
    'container.build_time' => 1563984967,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerN9z0fVx');
